package com.changrui.mysterious.domain.user.controller;

import com.changrui.mysterious.domain.user.dto.*;
import com.changrui.mysterious.domain.user.model.AppUser;
import com.changrui.mysterious.domain.user.repository.AppUserRepository;
import com.changrui.mysterious.domain.user.service.AdminService;
import com.changrui.mysterious.shared.dto.ApiResponse;
import com.changrui.mysterious.shared.exception.ValidationException;
import com.changrui.mysterious.shared.security.TokenService;
import jakarta.validation.Valid;
import java.security.SecureRandom;
import java.util.Map;
import java.util.regex.Pattern;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.ResponseEntity;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

/**
 * Authentication controller for user registration and login.
 */
@Slf4j
@RestController
@RequestMapping("/api/auth")
public class AuthController {

    @Autowired
    private AppUserRepository userRepository;

    @Autowired
    private AdminService adminService;

    @Autowired
    private com.changrui.mysterious.domain.profile.service.ProfileService profileService;

    @Autowired
    private TokenService tokenService;

    /**
     * Guest ids generated by the client: user_<epochMillis>_<base36 random>
     */
    private static final Pattern GUEST_ID_PATTERN = Pattern.compile("^user_\\d{10,16}_[a-z0-9]{1,16}$");

    private static final SecureRandom RANDOM = new SecureRandom();

    /**
     * Register a user and create their profile atomically (both or neither).
     */
    @Transactional
    @PostMapping("/register")
    public ResponseEntity<ApiResponse<AuthResponseDTO>> register(@Valid @RequestBody RegisterDTO dto) {
        if (userRepository.findByUsername(dto.username()).isPresent()) {
            throw new ValidationException("Username already taken");
        }

        AppUser newUser = new AppUser(dto.username(), dto.password(), dto.password());
        try {
            // Flush now so a concurrent registration of the same username fails here
            userRepository.saveAndFlush(newUser);
        } catch (DataIntegrityViolationException e) {
            throw new ValidationException("Username already taken");
        }

        // Same transaction as the user: if profile creation fails, the user is rolled back too
        com.changrui.mysterious.domain.profile.dto.CreateProfileRequest profileRequest = new com.changrui.mysterious.domain.profile.dto.CreateProfileRequest(
                newUser.getId(),
                dto.username(),
                null, // bio
                true, // isPublic
                dto.gender());
        com.changrui.mysterious.domain.profile.dto.ProfileResponse pr = profileService
                .createProfile(profileRequest);
        String avatarUrl = pr.avatarUrl();

        AuthResponseDTO response = new AuthResponseDTO(
                newUser.getId(),
                newUser.getUsername(),
                avatarUrl,
                "User registered successfully",
                tokenService.issue(newUser.getId(), false));

        return ResponseEntity.ok(ApiResponse.success("User registered successfully", response));
    }

    @PostMapping("/verify-admin")
    public ResponseEntity<ApiResponse<StartAdminSessionDTO>> verifyAdmin(@Valid @RequestBody AdminVerifyDTO dto) {
        try {
            adminService.validateAdminCode(dto.code());
        } catch (SecurityException e) {
            throw new ValidationException("Invalid admin code");
        }

        AdminService.AdminLevel level = adminService.getAdminLevel(dto.code());
        String role = level == AdminService.AdminLevel.SUPER_ADMIN ? "super_admin" : "admin";

        StartAdminSessionDTO response = new StartAdminSessionDTO(role, "Admin session started");

        return ResponseEntity.ok(ApiResponse.success("Admin verification successful", response));
    }

    @PostMapping("/login")
    public ResponseEntity<ApiResponse<AuthResponseDTO>> login(@Valid @RequestBody LoginDTO dto) {
        AppUser user = userRepository.findByUsername(dto.username())
                .orElseThrow(() -> new ValidationException("Invalid credentials"));

        if (!user.getPassword().equals(dto.password())) {
            throw new ValidationException("Invalid credentials");
        }

        String avatarUrl = null;
        try {
            com.changrui.mysterious.domain.profile.dto.ProfileResponse pr = profileService.getProfile(user.getId(),
                    user.getId());
            avatarUrl = pr.avatarUrl();
        } catch (Exception e) {
            // Silently fail if profile not found
        }

        AuthResponseDTO response = new AuthResponseDTO(
                user.getId(),
                user.getUsername(),
                avatarUrl,
                "Login successful",
                tokenService.issue(user.getId(), false));

        return ResponseEntity.ok(ApiResponse.success("Login successful", response));
    }

    /**
     * Issue a guest identity token.
     * Trust-on-first-use: a legacy client-generated guest id is kept (so the guest keeps ownership of
     * past messages) if it has the client format and is not a registered user id; otherwise a new one is generated.
     */
    @PostMapping("/guest")
    public ResponseEntity<ApiResponse<Map<String, String>>> guest(
            @RequestBody(required = false) Map<String, String> body) {
        String guestId = body != null ? body.get("guestId") : null;
        if (guestId == null || !GUEST_ID_PATTERN.matcher(guestId).matches() || userRepository.existsById(guestId)) {
            guestId = "user_" + System.currentTimeMillis() + "_" + randomBase36(9);
        }
        return ResponseEntity.ok(ApiResponse.success(
                Map.of("userId", guestId, "token", tokenService.issue(guestId, true))));
    }

    private static String randomBase36(int length) {
        StringBuilder sb = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            sb.append(Character.forDigit(RANDOM.nextInt(36), 36));
        }
        return sb.toString();
    }
}
